Implementation of the TCF v2 consent string spec
LiveRamp/iabconsent pull request #11
Opened 2020-03-10 02:31 UTC by adayNU

This change implements the newly released TCF v2 consent string spec.
More can be found on this here:

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2

Due to backward compatability issues, we have multiple similarly named
types, and functions. Until v1.1 is no longer expected in the wild, we
will continue to support this. We may later decide to create a v2 module
within the repo, or at a new location.

I'm honestly still not quite confident on how to implement the methods
EveryPurposeAllowed and VendorAllowed for the new type V2ParsedConsent,
and that may need to come in a subsequent PR.

2020-03-10 03:42 UTC, rupertchen requested changes
I don't expect to do a proper review of this change until the end of the week at the earliest. Is that going to be okay?

I made a cursory pass, but didn't look into the correctness of any of the code changes.

> Reviewed 5 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M21Pv1I2UBVfSmJI4Zu:b72vazw)* status: 5 of 12 files reviewed, 6 unresolved discussions (waiting on @adayNU, @elynnyap, and @rupertchen)

___
*[.gitignore, line 2 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21Q3PW6tRKv5XhFUc7:-M21Q3PW6tRKv5XhFUc8:bmllpxj) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/.gitignore#L2)):*
> ```ignore
> /vendor/
> .idea/*
> ```

Can we do without adding this rule?

I think these dev environment-specific rules should stay in on individuals' machines (e.g., `~/.config/git/ignore`) rather than added to project repos.
___
*[.travis.yml, line 16 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21R2iU4ykrwoK6tCUk:-M21R2iU4ykrwoK6tCUl:b1mjgl3) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/.travis.yml#L16)):*
> ```YAML
> before_install:
>   - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
>   - go mod download
> ```

I assume we don't intend to drop support for older versions of Go since the change above only adds 1.13. Does travis support a way to run different setups for different versions, or would this config need to do it via shell scripting?
___
*[parse.go, line 128 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21SxrJ3QwUvP6gjBoD:-M21SxrK48aHFmONiszH:bkre745) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L128)):*
> ```Go
> }
> 
> // Parse takes a base64 Raw URL Encoded string which represents a TCF v1.1
> ```

Typo: "Parse" -> "Parsev1"
___
*[parse.go, line 168 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21SsOwDAiSEYfCqIIP:-M21SsOwDAiSEYfCqIIQ:bkrdjes) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L168)):*
> ```Go
> }
> 
> // Parse takes a base64 Raw URL Encoded string which represents a TCF v2
> ```

Typo: "Parse" -> "ParseV2"
___
*[parse.go, line 288 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21TIAZEGf396y0Lf43:-M21TIAZEGf396y0Lf44:b1an9c5) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L288)):*
> ```Go
> )
> 
> // ParseWithoutVersion allows the caller to pass any valid consent string
> ```

Mismatch between doc and func?
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21TkVc29IDIEB6bKiS:-M21TkVc29IDIEB6bKiT:bwqfyts) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/README.md#L5)):*
> ```Markdown
> [![Go Report Card](https://goreportcard.com/badge/github.com/LiveRamp/iabconsent)](https://goreportcard.com/report/github.com/LiveRamp/iabconsent)
> 
> A Golang implementation of the IAB Consent String 1.1 Spec as well as the IAB Transparency and Consent String v2.0.
> ```

Nit: Add hard line-wraps or re-wrap edited text.

I'm a proponent of formatting markdown source when it appears as documentation in code repositories to be as readable while in the raw form as possible while producing the desired rendered form.

- Developers work close to plain text most of the time and shouldn't need to render documentation before reading it comfortably.
- Modern diffing tools are generally competent at rendering multi-line diffs where text is shifted vs modified.


<!-- Sent from Reviewable.io -->

2020-03-10 17:17 UTC, adayNU reviewed
@rupertchen no rush. EOW is okay. (Also have @elynnyap as a reviewer)

> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M24RnbBEKLjOAxtm6fh:b-gerto5)* status: 3 of 11 files reviewed, 6 unresolved discussions (waiting on @elynnyap and @rupertchen)

___
*[.gitignore, line 2 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21Q3PW6tRKv5XhFUc7:-M24N-k76mU7Ha-hyvml:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/.gitignore#L2)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Can we do without adding this rule?

I think these dev environment-specific rules should stay in on individuals' machines (e.g., `~/.config/git/ignore`) rather than added to project repos.
</blockquote></details>

Done.
___
*[.travis.yml, line 16 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21R2iU4ykrwoK6tCUk:-M24N1022TXC1Cv0lZc2:bkbjlu7) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/.travis.yml#L16)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I assume we don't intend to drop support for older versions of Go since the change above only adds 1.13. Does travis support a way to run different setups for different versions, or would this config need to do it via shell scripting?
</blockquote></details>

I think this should be working now.
___
*[parse.go, line 128 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21SxrJ3QwUvP6gjBoD:-M24OeT92KICtUsjRJQH:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L128)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Typo: "Parse" -> "Parsev1"
</blockquote></details>

Done.
___
*[parse.go, line 168 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21SsOwDAiSEYfCqIIP:-M24OdzD32uDx6oddfi8:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L168)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Typo: "Parse" -> "ParseV2"
</blockquote></details>

Done.
___
*[parse.go, line 288 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21TIAZEGf396y0Lf43:-M24NIYk59RX9O3GmlmF:be15t2g) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/parse.go#L288)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Mismatch between doc and func?
</blockquote></details>

Errr yeah I changed my mind on implementation, my bad. Fixed.
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/liveramp/iabconsent/11#-M21TkVc29IDIEB6bKiS:-M24RTZEAQgb335c3KBy:bm3flbp) ([raw file](https://github.com/liveramp/iabconsent/blob/b4ad1d113bf3fbba19cef2f967055ff00b1fab29/README.md#L5)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: Add hard line-wraps or re-wrap edited text.

I'm a proponent of formatting markdown source when it appears as documentation in code repositories to be as readable while in the raw form as possible while producing the desired rendered form.

- Developers work close to plain text most of the time and shouldn't need to render documentation before reading it comfortably.
- Modern diffing tools are generally competent at rendering multi-line diffs where text is shifted vs modified.

</blockquote></details>

Switched to reference style images.


<!-- Sent from Reviewable.io -->

2020-03-20 15:30 UTC, imang1 requested changes
> Reviewed 8 of 12 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11)* status: all files reviewed, 12 unresolved discussions (waiting on @adayNU and @rupertchen)

___
*[parse.go, line 124 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sSLXT2bZdpolC_MuB:-M2sSLXUClqSlcQZE6on:bocovmd) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L124)):*
> ```Go
> //
> // Deprecated: Use ParseV1 to parse V1 consent strings.
> func Parse(s string) (*ParsedConsent, error) {
> ```

if a user uses Parse with a v2 string, what is the behavior? 
___
*[parse.go, line 185 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sO616EUTDMSCJEbwb:-M2sO616EUTDMSCJEbwc:bc1qbwj) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L185)):*
> ```Go
> 	var r = NewConsentReader(b)
> 
> 	// This block of code directly describes the format of the payload.
> ```

Is it worth it to link the IAB consent string Core String format here? I'm not sure how people are going to use this, but could be helpful to see what all of these bits mean
___
*[parse.go, line 186 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sLFvo17SAgUD-M6qb:-M2sLFvo17SAgUD-M6qc:b4s586j) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L186)):*
> ```Go
> 
> 	// This block of code directly describes the format of the payload.
> 	var p = &V2ParsedConsent{}
> ```

should there be any error handling for a malformed payload (say version shorted/longer than 6 bits)? Or is that handled in the `DecodeString(ss[0])`?
___
*[parse.go, line 255 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sPcRX36pBoqUICOha:-M2sPcRX36pBoqUICOhb:b-8o70fl) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L255)):*
> ```Go
> 			p.PublisherTCEntry = ptc
> 		default:
> 			// panic?
> ```

if we get here, that means we cannot establish whether we have consent right? how are we indicating that we do not have consent for this user? would it be better to indicate the same here, maybe plus an error message that we could not establish consent with oob, instead of just panicking? 
___
*[v2_parsed_consent.go, line 238 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sVIHwBPjr_bI5hgOu:-M2sVIHwBPjr_bI5hgOv:bd3wfry) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/v2_parsed_consent.go#L238)):*
> ```Go
> )
> 
> // SpecialFeature is an enum type for special purposes.
> ```

nit: SpecialFeature should be SpecialPurpose
___
*[v2_parsed_consent_fixture_test.go, line 11 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sXqDx7lFOdgrEcQav:-M2sXqDx7lFOdgrEcQaw:b7hodgs) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/v2_parsed_consent_fixture_test.go#L11)):*
> ```Go
> var v2TestTime = time.Unix(1583436280, 9*nsPerDs).UTC()
> 
> // Consent fixtures have been generated using the tool at https://iabtcf.com/encode.
> ```

:+1: for this site-thought you would have to have A Beautiful Mind moment to figure out all those vendors 


<!-- Sent from Reviewable.io -->

2020-03-23 03:19 UTC, rupertchen requested changes
Initial full pass complete.

> Reviewed 5 of 12 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M34Oi515wul42Ft_53o:b18bjh2)* status: all files reviewed, 26 unresolved discussions (waiting on @adayNU and @imang1)

___
*[doc.go, line 4 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33pzfx8CTyXtWcNiuO:-M33pzfx8CTyXtWcNiuP:bkahtvf) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/doc.go#L4)):*
> ```Go
> 
> Package iabconsent provides structs and methods for parsing vendor consent strings as defined by the IAB.
> Current two versions of consent strings are supported.
> ```

Nit: When linking into GitHub, I prefer to use the URL's canonical form rather than a branch because the content will not change (unless removed entirely). GH shortcut to expand the URL is `y`.
___
*[parse.go, line 138 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33rVTL3w3xIVAGpfQh:-M33rVTL3w3xIVAGpfQi:b87oy31) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L138)):*
> ```Go
> 	var b, err = base64.RawURLEncoding.DecodeString(s)
> 	if err != nil {
> 		return nil, errors.Wrap(err, "parse consent string")
> ```

Idea: mention "v1" in the error.
___
*[parse.go, line 180 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33rdA01mEItZultzPS:-M33rdA01mEItZultzPT:b-89klw) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L180)):*
> ```Go
> 	var b, err = base64.RawURLEncoding.DecodeString(ss[0])
> 	if err != nil {
> 		return nil, errors.Wrap(err, "parse consent string")
> ```

Idea: mention "v2" in the error.
___
*[parse.go, line 185 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sO616EUTDMSCJEbwb:-M33rlXp4NbCovYu1QO_:bqv0t3j) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L185)):*
<details><summary><i>Previously, imang1 (Isabel Mangan) wrote…</i></summary><blockquote>

Is it worth it to link the IAB consent string Core String format here? I'm not sure how people are going to use this, but could be helpful to see what all of these bits mean
</blockquote></details>

I think this would be helpful.

Although it's mentioned in the package's docs, repeating it here as source commentary for developers working with this code would be convenient. The package docs are somewhat "far away" and a developer could easily not realize they exist. Same goes for comments by the v1 implementation.
___
*[parse.go, line 186 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sLFvo17SAgUD-M6qb:-M33uKZj1Gj3O_grrtqu:bvfra91) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L186)):*
<details><summary><i>Previously, imang1 (Isabel Mangan) wrote…</i></summary><blockquote>

should there be any error handling for a malformed payload (say version shorted/longer than 6 bits)? Or is that handled in the `DecodeString(ss[0])`?
</blockquote></details>

I have several things to say related to this, so I'll try to break them apart.

1. `base64.RawURLEncoding.DecodeString(ss[0])` will catch errors in Base64 encoding, but it is blind to everything else, including the entire payload being too short.
2. When I wrote `bits.Reader`, I designed it so users had the option to either check for errors as they went, or batch a sequence of reads before checking.

   My thought process when I wrote the previous version of `iabconsent.Parse` was to make this block of "bit grabbing" more readable and easier to line up with the consent string spec. If a field in the payload was the wrong length, it would probably (hopefully?) misalign a field where the format is more strict. For primitive reads, like bool and int, we just don't know if the bit we're reading is malformed or not in isolation.

   That said, now that there are two versions of consent strings in existence, and this package handles both, I think it makes sense to validate `p.Version` early on and bail if the value is unexpected. It's nice to short circuit useless work, but more importantly, we could provide a more helpful error message. Imagine some dev trying to debug some error claiming an invalid sequence in the vendors when it turns out it wasn't even a v2 consent string.

   See:
   - https://github.com/rupertchen/go-bits/blob/e6e22cd48e4f78d8fb537a2aa7b63f3debb231cc/reader.go#L14-L17
   - https://godoc.org/github.com/rupertchen/go-bits#Reader
___
*[parse.go, line 222 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M34-1Al2XphbhU1DnNR:-M34-1Al2XphbhU1DnNS:b-2m7mdr) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L222)):*
> ```Go
> 	}
> 
> 	p.NumPubRestrictions, _ = r.ReadInt(16)
> ```

NumPubRestrictions is 12 bits. :scream: 
___
*[parse.go, line 224 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3417iv5nV2lxyTfEII:-M3417iv5nV2lxyTfEIJ:b-9ibg2d) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L224)):*
> ```Go
> 	p.NumPubRestrictions, _ = r.ReadInt(16)
> 
> 	for i := 0; i < p.NumPubRestrictions; i++ {
> ```

Idea: Extract this looping to `ReadPubRestrictionEntries`, similar to `ReadRangeEntries`.

I think it makes this hard-to-read bit-parsing a little bit more structured and makes it easy to write unit tests on just this part.
___
*[parse.go, line 231 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M344oyG9Bcv5a7tgUqZ:-M344oyG9Bcv5a7tgUq_:b-1mqw9j) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L231)):*
> ```Go
> 	}
> 
> 	for _, oob := range ss[1:] {
> ```

Nit: Technically publisher TC is not out-of-band signaling. Rename `oob` to `segment` or `s`? Related, since `ss` has such as large scope (lots of lines) I think it's worth giving it the longer name `segments`.
___
*[parse.go, line 234 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M343OMQ1hZdkqvzIGDx:-M343OMQ1hZdkqvzIGDy:b-gytorr) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L234)):*
> ```Go
> 		b, err = base64.RawURLEncoding.DecodeString(oob)
> 		if err != nil {
> 			return nil, errors.Wrap(err, "parse consent string")
> ```

Nit: Mention v2, or potentially be even more specific and mention this is parsing the Nth segment.

Nit: Return the `p` that we have so far so a debugging developer has a chance at seeing how far it did get before parsing stopped. This is inline with what parse already does by relying on the ConsentReader to forever error once it errors once. This was a conscious decision on my part, but perhaps it should be explicitly stated somewhere.
___
*[parse.go, line 239 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M345sq1EQmWNOnuUCFQ:-M345sq2BRLPGjhtL7xQ:bbfu5wk) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L239)):*
> ```Go
> 		r = NewConsentReader(b)
> 		var st, _ = r.ReadSegmentType()
> 		switch st {
> ```

Should it be an error for any of these optional segments to appear more than once?
___
*[parse.go, line 244 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M346YBjAxZGyhenfCYh:-M346YBjAxZGyhenfCYi:b3zc4ox) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L244)):*
> ```Go
> 		case AllowedVendors:
> 			p.OOBAllowedVendors = parseVendors(r, st)
> 		case PublisherTC:
> ```

Nit: Here also, I like the idea of `ReadPublisherTC` and even `ReadOOBVendorList` being added to the ConsentReader.

It seems fine to me that in V2, "reading a consent string" extends beyond the core and to the optional segments. I also like the consistency of "read" pulling sequential bits and "parse" taking a s [...]

2020-03-24 00:30 UTC, adayNU reviewed
@rupertchen / @imang1 PTAL. Should have covered most changes. Please call out anything needing a unit test.

> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M38wf_k0pGqa5lenmig:b-2ihpke)* status: 5 of 11 files reviewed, 14 unresolved discussions (waiting on @imang1 and @rupertchen)

___
*[doc.go, line 4 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33pzfx8CTyXtWcNiuO:-M38PA2pBhamd3UEiQio:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/doc.go#L4)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: When linking into GitHub, I prefer to use the URL's canonical form rather than a branch because the content will not change (unless removed entirely). GH shortcut to expand the URL is `y`.
</blockquote></details>

Done.
___
*[parse.go, line 124 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sSLXT2bZdpolC_MuB:-M38FISK2fcH9-lhtoQq:bmxfmsv) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L124)):*
<details><summary><i>Previously, imang1 (Isabel Mangan) wrote…</i></summary><blockquote>

if a user uses Parse with a v2 string, what is the behavior? 
</blockquote></details>

The'll get an error (same as if they called `ParseV1`). The only callers of this function _should_ be people too lazy to update their v1 implementation, and is only retained to keep those from breaking if they update this dependency.
___
*[parse.go, line 138 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33rVTL3w3xIVAGpfQh:-M38pwZD6_Q-_ZzfUB9M:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L138)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Idea: mention "v1" in the error.
</blockquote></details>

Done.
___
*[parse.go, line 180 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M33rdA01mEItZultzPS:-M38pxQc9h_5aeofqvS9:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L180)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Idea: mention "v2" in the error.
</blockquote></details>

Done.
___
*[parse.go, line 185 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sO616EUTDMSCJEbwb:-M38pyWh-mloHCUyQ752:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L185)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I think this would be helpful.

Although it's mentioned in the package's docs, repeating it here as source commentary for developers working with this code would be convenient. The package docs are somewhat "far away" and a developer could easily not realize they exist. Same goes for comments by the v1 implementation.
</blockquote></details>

Done.
___
*[parse.go, line 186 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M2sLFvo17SAgUD-M6qb:-M38q0Kr-JB68IApFbj3:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L186)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I have several things to say related to this, so I'll try to break them apart.

1. `base64.RawURLEncoding.DecodeString(ss[0])` will catch errors in Base64 encoding, but it is blind to everything else, including the entire payload being too short.
2. When I wrote `bits.Reader`, I designed it so users had the option to either check for errors as they went, or batch a sequence of reads before checking.

   My thought process when I wrote the previous version of `iabconsent.Parse` was to make this block of "bit grabbing" more readable and easier to line up with the consent string spec. If a field in the payload was the wrong length, it would probably (hopefully?) misalign a field where the format is more strict. For primitive reads, like bool and int, we just don't know if the bit we're reading is malformed or not in isolation.

   That said, now that there are two versions of consent strings in existence, and this package handles both, I think it makes sense to validate `p.Version` early on and bail if the value is unexpected. It's nice to short circuit useless work, but more importantly, we could provide a more helpful error message. Imagine some dev trying to debug some error claiming an invalid sequence in the vendors when it turns out it wasn't even a v2 consent string.

   See:
   - https://github.com/rupertchen/go-bits/blob/e6e22cd48e4f78d8fb537a2aa7b63f3debb231cc/reader.go#L14-L17
   - https://godoc.org/github.com/rupertchen/go-bits#Reader
</blockquote></details>

Done.
___
*[parse.go, line 222 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M34-1Al2XphbhU1DnNR:-M38GF-E90m2NY3TuyDr:b-u4sguo) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L222)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

NumPubRestrictions is 12 bits. :scream: 
</blockquote></details>

Oh lawd. Fixed.
___
*[parse.go, line 224 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3417iv5nV2lxyTfEII:-M38JB70CPddL7zFxy7R:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L224)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Idea: Extract this looping to `ReadPubRestrictionEntries`, similar to `ReadRangeEntries`.

I think it makes this hard-to-read bit-parsing a little bit more structured and makes it easy to write unit tests on just this part.
</blockquote></details>

Done.
___
*[parse.go, line 231 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M344oyG9Bcv5a7tgUqZ:-M38JWiPAu0tRV13H7cK:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L231)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: Technically publisher TC is not out-of-band signaling. Rename `oob` to `segment` or `s`? Related, since `ss` has such as large scope (lots of lines) I think it's worth giving it the longer name `segments`.
</blockquote></details>

Done.
___
*[parse.go, line 234 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M343OMQ1hZdkqvzIGDx:-M38KmZq-NS_5vXAbiZ_:bx4nh62) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L234)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: Mention v2, or potentially be even more specific and mention this is parsing the Nth segment.

Nit: Return the `p` that we have so far so a debugging developer has a chance at seeing how far it did get before parsing stopped. This is inline with what parse already does by relying on the ConsentReader to forever error once it errors once. This was a conscious decision on my part, but perhaps it should be explicitly stated somewhere.
</blockquote></details>

Done and done.
___
*[parse.go, line 239 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M345sq1EQmWNOnuUCFQ:-M38s4lf2gwNbeYD62iU:b-uc14zs) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L239)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Should it be an error for any of these optional segments to appear more than once?
</blockquote></details>

I wonder if the complexity is worth it. But technically there are rules around which can appear together in the spec.
___
*[parse.go, line 244 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M346YBjAxZGyhenfCYh:-M38 [...]

2020-03-24 19:28 UTC, imang1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M3D04LRD83lYSZ2cShp:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @rupertchen)



<!-- Sent from Reviewable.io -->

2020-03-25 20:10 UTC, rupertchen requested changes
I think this should also error in ParseV1 receives a string that doesn't have "1" in its version field. The other suggestion are up to you.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M3IIq7H1zPuqc9uHlS5:b-qrqek8)* status: all files reviewed, 5 unresolved discussions (waiting on @adayNU and @rupertchen)

___
*[parse.go, line 239 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M345sq1EQmWNOnuUCFQ:-M3IGCVg4to1SrHGre2N:b-o6knpq) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L239)):*
<details><summary><i>Previously, adayNU (Andy Day) wrote…</i></summary><blockquote>

I wonder if the complexity is worth it. But technically there are rules around which can appear together in the spec.
</blockquote></details>

I think it'd be a good idea to error if a segment's property is already non-zero, but I'm changing the comment disposition so it's not a blocker.

I don't think it's worth explicitly checking for the valid combinations, just that we don't overwrite existing parsed segments because then something is definitely wrong.
___
*[parse.go, line 148 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3EEXnn5mV5_hvAI1Lr:-M3EEXnn5mV5_hvAI1Ls:b-h90a22) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L148)):*
> ```Go
> }
> 
> // ReadVendors reads in a vendor list representing either disclosed or allowed vendor lists.
> ```

Nit: The spec groups the bits for the segment type with the rest of this list. I'm not sure of how to best make it clear that ReadVendors and ReadPublisherTCEntry both assume the segment type bits have already been read, but it's a potential gotcha for a future dev. Perhaps a callout in each func's godoc is all that's needed.
___
*[parse.go, line 229 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3IFjnd0YcaWD18fefA:-M3IFjnd0YcaWD18fefB:b-84kx9d) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L229)):*
> ```Go
> 	// This block of code directly describes the format of the payload.
> 	var p = &ParsedConsent{}
> 	p.Version, _ = r.ReadInt(6)
> ```

Check version value here as well?
___
*[parse.go, line 274 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3IF6AJDYCOKRY_dSL6:-M3IF6AJDYCOKRY_dSL7:b8m14nc) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L274)):*
> ```Go
> 	var p = &V2ParsedConsent{}
> 	p.Version, _ = r.ReadInt(6)
> 	if p.Version != 2 {
> ```

Is `iabconsent.V2`'s value intended to match this or is it more or less coincidence that it happens to be 2 right now. I guess this is really a question about all `TCFVersion` enums.


<!-- Sent from Reviewable.io -->

2020-03-30 16:52 UTC, adayNU reviewed
@rupertchen PTAL!

> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M3gLor_7c581L-8kJAF:b-3owicr)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @imang1 and @rupertchen)

___
*[parse.go, line 239 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M345sq1EQmWNOnuUCFQ:-M3gKp9yB-DOXeHqp1DK:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L239)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

I think it'd be a good idea to error if a segment's property is already non-zero, but I'm changing the comment disposition so it's not a blocker.

I don't think it's worth explicitly checking for the valid combinations, just that we don't overwrite existing parsed segments because then something is definitely wrong.
</blockquote></details>

Done.
___
*[parse.go, line 283 at r2](https://reviewable.io/reviews/liveramp/iabconsent/11#-M34CZz85OekAfKmzPrZ:-M3gLsti21uClqf6y0Fw:b9wzcy1) ([raw file](https://github.com/liveramp/iabconsent/blob/34a30d5e709720fef86f2f5c0950d444597dc5ad/parse.go#L283)):*
<details><summary><i>Previously, adayNU (Andy Day) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@rupertchen fyi you're still blocking here.
___
*[parse.go, line 148 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3EEXnn5mV5_hvAI1Lr:-M3gLnsd99dtXklk6h7k:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L148)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Nit: The spec groups the bits for the segment type with the rest of this list. I'm not sure of how to best make it clear that ReadVendors and ReadPublisherTCEntry both assume the segment type bits have already been read, but it's a potential gotcha for a future dev. Perhaps a callout in each func's godoc is all that's needed.
</blockquote></details>

Done.
___
*[parse.go, line 229 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3IFjnd0YcaWD18fefA:-M3gKrSY2klA7KL5FaK0:b-896fix) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L229)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Check version value here as well?
</blockquote></details>

Done.
___
*[parse.go, line 274 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3IF6AJDYCOKRY_dSL6:-M3gKsm297x2udJJ4JlR:b-o5xtml) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L274)):*
<details><summary><i>Previously, rupertchen (Rupert Chen) wrote…</i></summary><blockquote>

Is `iabconsent.V2`'s value intended to match this or is it more or less coincidence that it happens to be 2 right now. I guess this is really a question about all `TCFVersion` enums.
</blockquote></details>

I think its intended to match this.


<!-- Sent from Reviewable.io -->

2020-03-30 20:47 UTC, rupertchen approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I left some optional remarks.

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/liveramp/iabconsent/11#-:-M3hBemNBdrcbbRy_4FN:bm728yo)* status: all files reviewed, 1 unresolved discussion (waiting on @adayNU)

___
*[parse.go, line 274 at r3](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3IF6AJDYCOKRY_dSL6:-M3hB3LkAxk5H0Rq0mv3:butv8uu) ([raw file](https://github.com/liveramp/iabconsent/blob/4602bc6a9b693ed22dea01c7e022d44263234ae8/parse.go#L274)):*
<details><summary><i>Previously, adayNU (Andy Day) wrote…</i></summary><blockquote>

I think its intended to match this.
</blockquote></details>

If it is expected to match, then I suggest `p.Version != V2` (and use V1 in ParseV1). Making this an optional suggestion.
___
*[parse.go, line 334 at r4](https://reviewable.io/reviews/liveramp/iabconsent/11#-M3hBUSOCviWhsL9n_54:-M3hBUSOCviWhsL9n_55:bpc9so) ([raw file](https://github.com/liveramp/iabconsent/blob/43f03c98171f9e8b2ed59e58708b04695a901f82/parse.go#L334)):*
> ```Go
> 		case DisclosedVendors:
> 			if p.OOBDisclosedVendors != nil {
> 				return p, errors.New("multiple disclosed vendors segments passed ")
> ```

Nit: All these error messages end in a space? :thinking: 


<!-- Sent from Reviewable.io -->

2020-03-30 20:54 UTC, merged